package com.rsargsyan.probarr.main_ctx.core.domain.valueobject;

public enum AudioAuthor {
  HDREZKA,
  HDREZKA_18PLUS,
  TVSHOWS,
  LOSTFILM,
  BRAVO_RECORDS_GEORGIA,
  READ_HEAD_SOUND,
  JASKIER,
  JASKIER_18PLUS,
  VIRUSEPROJECT,
  VIRUSEPROJECT_18PLUS,
  MOVIE_DALEN,
  POSTMODERN,
  KIRILLICA,
  IVI,
  KINOMANIA,
  ONE_PLUS_ONE,
  KINAKONG,
  MOVIE_DUBBING,
  PIFAGOR,
  NOVAMEDIA,
  RENTV,
  KRAVEC_RECORDS
}
