services:
  backend:
    image: rsargsyan/probarr-backend:latest
    ports:
      - "${BACKEND_PORT:-8091}:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-postgres}
      ADMIN_FIREBASE_PROJECT_ID: ${ADMIN_FIREBASE_PROJECT_ID}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      GRABBERR_BASE_URL: ${GRABBERR_BASE_URL}
      GRABBERR_API_KEY_ID: ${GRABBERR_API_KEY_ID}
      GRABBERR_API_KEY: ${GRABBERR_API_KEY}
      JACKETT_BASE_URL: ${JACKETT_BASE_URL}
      JACKETT_API_KEY: ${JACKETT_API_KEY}
      TMDB_API_KEY: ${TMDB_API_KEY}
      TVDB_API_KEY: ${TVDB_API_KEY}
      LOGGING_LEVEL_COM_RSARGSYAN_PROBARR: ${LOGGING_LEVEL_COM_RSARGSYAN_PROBARR:-INFO}
      JACKETT_TORRENT_DOWNLOAD_TIMEOUT_SECONDS: ${JACKETT_TORRENT_DOWNLOAD_TIMEOUT_SECONDS:-10}
      MOVIE_FILE_DOWNLOADING_TIMEOUT_SECONDS: ${MOVIE_FILE_DOWNLOADING_TIMEOUT_SECONDS:-172800}
      MOVIE_FILE_MIN_DOWNLOAD_SPEED_BYTES: ${MOVIE_FILE_MIN_DOWNLOAD_SPEED_BYTES:-50000}
      PROBARR_S3_ENDPOINT: ${PROBARR_S3_ENDPOINT}
      TVSHOW_ENRICHMENT_INTERVAL_SECONDS: ${TVSHOW_ENRICHMENT_INTERVAL_SECONDS:-60}
      TVSHOW_SCAN_INTERVAL_SECONDS: ${TVSHOW_SCAN_INTERVAL_SECONDS:-60}
      PROBARR_S3_BUCKET: {PROBARR_S3_BUCKET:-probarr}
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "minio.local:host-gateway"
    restart: unless-stopped

  admin-ui:
    image: rsargsyan/probarr-admin-ui:latest
    ports:
      - "${ADMIN_UI_PORT:-5177}:80"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_ADMIN_FIREBASE_API_KEY: ${VITE_ADMIN_FIREBASE_API_KEY}
      VITE_ADMIN_FIREBASE_AUTH_DOMAIN: ${VITE_ADMIN_FIREBASE_AUTH_DOMAIN}
      VITE_ADMIN_FIREBASE_PROJECT_ID: ${VITE_ADMIN_FIREBASE_PROJECT_ID}
      VITE_ADMIN_FIREBASE_STORAGE_BUCKET: ${VITE_ADMIN_FIREBASE_STORAGE_BUCKET}
      VITE_ADMIN_FIREBASE_MESSAGING_SENDER_ID: ${VITE_ADMIN_FIREBASE_MESSAGING_SENDER_ID}
      VITE_ADMIN_FIREBASE_APP_ID: ${VITE_ADMIN_FIREBASE_APP_ID}
    restart: unless-stopped

  web-ui:
    image: rsargsyan/probarr-web-ui:latest
    ports:
      - "${WEB_UI_PORT:-5178}:80"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
      VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
      VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
    restart: unless-stopped

