declare global {
  interface Window {
    __PROBARR_ADMIN_ENV__?: Record<string, string>
  }
}

const r = window.__PROBARR_ADMIN_ENV__

export const env = {
  VITE_API_BASE_URL: r?.VITE_API_BASE_URL ?? import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8080',
  VITE_ADMIN_FIREBASE_API_KEY: r?.VITE_ADMIN_FIREBASE_API_KEY ?? import.meta.env.VITE_ADMIN_FIREBASE_API_KEY,
  VITE_ADMIN_FIREBASE_AUTH_DOMAIN: r?.VITE_ADMIN_FIREBASE_AUTH_DOMAIN ?? import.meta.env.VITE_ADMIN_FIREBASE_AUTH_DOMAIN,
  VITE_ADMIN_FIREBASE_PROJECT_ID: r?.VITE_ADMIN_FIREBASE_PROJECT_ID ?? import.meta.env.VITE_ADMIN_FIREBASE_PROJECT_ID,
  VITE_ADMIN_FIREBASE_STORAGE_BUCKET: r?.VITE_ADMIN_FIREBASE_STORAGE_BUCKET ?? import.meta.env.VITE_ADMIN_FIREBASE_STORAGE_BUCKET,
  VITE_ADMIN_FIREBASE_MESSAGING_SENDER_ID: r?.VITE_ADMIN_FIREBASE_MESSAGING_SENDER_ID ?? import.meta.env.VITE_ADMIN_FIREBASE_MESSAGING_SENDER_ID,
  VITE_ADMIN_FIREBASE_APP_ID: r?.VITE_ADMIN_FIREBASE_APP_ID ?? import.meta.env.VITE_ADMIN_FIREBASE_APP_ID,
}
