#!/bin/sh
set -e

cat > /usr/share/nginx/html/env.js << EOF
Object.defineProperty(window, '__PROBARR_ADMIN_ENV__', {
  value: {
    VITE_API_BASE_URL: '${VITE_API_BASE_URL}',
    VITE_ADMIN_FIREBASE_API_KEY: '${VITE_ADMIN_FIREBASE_API_KEY}',
    VITE_ADMIN_FIREBASE_AUTH_DOMAIN: '${VITE_ADMIN_FIREBASE_AUTH_DOMAIN}',
    VITE_ADMIN_FIREBASE_PROJECT_ID: '${VITE_ADMIN_FIREBASE_PROJECT_ID}',
    VITE_ADMIN_FIREBASE_STORAGE_BUCKET: '${VITE_ADMIN_FIREBASE_STORAGE_BUCKET}',
    VITE_ADMIN_FIREBASE_MESSAGING_SENDER_ID: '${VITE_ADMIN_FIREBASE_MESSAGING_SENDER_ID}',
    VITE_ADMIN_FIREBASE_APP_ID: '${VITE_ADMIN_FIREBASE_APP_ID}',
  },
  writable: false,
});
EOF

exec nginx -g 'daemon off;'
