spring.application.name=main-ctx

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/probarr}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Admin Firebase project
admin.firebase.project-id=${ADMIN_FIREBASE_PROJECT_ID:sprite-6193a}

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/${FIREBASE_PROJECT_ID:sprite-6193a}

grabberr.base-url=${GRABBERR_BASE_URL:http://localhost:8082}
jackett.base-url=${JACKETT_BASE_URL:http://localhost:9117}
jackett.api-key=${JACKETT_API_KEY:}
prowlarr.base-url=${PROWLARR_BASE_URL:http://localhost:9696}
prowlarr.api-key=${PROWLARR_API_KEY:}
indexer.movie-categories=${INDEXER_MOVIE_CATEGORIES:2000,2040,2045,2060}
movie.scan-interval-hours=${MOVIE_SCAN_INTERVAL_HOURS:24}
grabberr.api-key-id=${GRABBERR_API_KEY_ID}
grabberr.api-key=${GRABBERR_API_KEY}

db-scheduler.enabled=true

logging.level.com.rsargsyan.probarr=INFO
